[workspace]
members = [
    "viz",
    "mpu6050",
    "st7735-test",
    "imu-display",
    "body_km",
    "body_viz",
    "tca9548a",
    "mpu6050_firmware",
]

[workspace.dependencies]
mpu6050_firmware = { path = "./mpu6050_firmware" }
