[package]
name = "xiao-blink-test"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-halt = "1.0"
nrf52840-hal = { version = "0.19.0", features = ["rt"] }
embedded-hal = "0.2.7"

[profile.release]
opt-level = "s"
lto = true
panic = "abort"
